<?php
namespace App\Tests\Functions\DB;

use App\Functions\DB\SystemTables;
use PHPUnit\Framework\TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2018-01-02 at 16:09:06.
 */
class SystemTablesTest extends TestCase
{

    /**
     * @var SystemTables
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new SystemTables('');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }
    
    public function testGetSystemTables()
    {
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );    
    }
}
