<?php
namespace App\Tests\Entity;

use PHPUnit\Framework\TestCase;
use App\Entity\Role;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2018-01-02 at 16:09:17.
 */
class RoleTest extends TestCase
{

    /**
     * @var Role
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Role;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }
    
    public function testGetRole()
    {
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );    
    }
}
