<?php
namespace App\Tests\Entity;

use App\Entity\UserRole;
use PHPUnit\Framework\TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2018-01-02 at 16:09:17.
 */
class UserRoleTest extends TestCase
{

    /**
     * @var UserRole
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new UserRole;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }
    
    public function testGetUserRole()
    {
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );    
    }
}
