<?php
namespace App\Entity;

use PHPUnit\Framework\TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2018-01-02 at 16:09:17.
 */
class User_oldTest extends TestCase
{

    /**
     * @var User_old
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new User_old;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers App\Entity\User_old::getRoles
     * @todo   Implement testGetRoles().
     */
    public function testGetRoles()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers App\Entity\User_old::getSalt
     * @todo   Implement testGetSalt().
     */
    public function testGetSalt()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers App\Entity\User_old::eraseUserCredentials
     * @todo   Implement testEraseUserCredentials().
     */
    public function testEraseUserCredentials()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers App\Entity\User_old::eraseCredentials
     * @todo   Implement testEraseCredentials().
     */
    public function testEraseCredentials()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers App\Entity\User_old::getOldpassword
     * @todo   Implement testGetOldpassword().
     */
    public function testGetOldpassword()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers App\Entity\User_old::setOldpassword
     * @todo   Implement testSetOldpassword().
     */
    public function testSetOldpassword()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers App\Entity\User_old::getId
     * @todo   Implement testGetId().
     */
    public function testGetId()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers App\Entity\User_old::setUsername
     * @todo   Implement testSetUsername().
     */
    public function testSetUsername()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers App\Entity\User_old::getUsername
     * @todo   Implement testGetUsername().
     */
    public function testGetUsername()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers App\Entity\User_old::setFullname
     * @todo   Implement testSetFullname().
     */
    public function testSetFullname()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers App\Entity\User_old::getFullname
     * @todo   Implement testGetFullname().
     */
    public function testGetFullname()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers App\Entity\User_old::setImage
     * @todo   Implement testSetImage().
     */
    public function testSetImage()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers App\Entity\User_old::getImage
     * @todo   Implement testGetImage().
     */
    public function testGetImage()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers App\Entity\User_old::setLocale
     * @todo   Implement testSetLocale().
     */
    public function testSetLocale()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers App\Entity\User_old::getLocale
     * @todo   Implement testGetLocale().
     */
    public function testGetLocale()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers App\Entity\User_old::setRole
     * @todo   Implement testSetRole().
     */
    public function testSetRole()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers App\Entity\User_old::getRole
     * @todo   Implement testGetRole().
     */
    public function testGetRole()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers App\Entity\User_old::setPassword
     * @todo   Implement testSetPassword().
     */
    public function testSetPassword()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers App\Entity\User_old::getPassword
     * @todo   Implement testGetPassword().
     */
    public function testGetPassword()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers App\Entity\User_old::setEmail
     * @todo   Implement testSetEmail().
     */
    public function testSetEmail()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers App\Entity\User_old::getEmail
     * @todo   Implement testGetEmail().
     */
    public function testGetEmail()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers App\Entity\User_old::setIsActive
     * @todo   Implement testSetIsActive().
     */
    public function testSetIsActive()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers App\Entity\User_old::getIsActive
     * @todo   Implement testGetIsActive().
     */
    public function testGetIsActive()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers App\Entity\User_old::setLastIp
     * @todo   Implement testSetLastIp().
     */
    public function testSetLastIp()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers App\Entity\User_old::getLastIp
     * @todo   Implement testGetLastIp().
     */
    public function testGetLastIp()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers App\Entity\User_old::setLastTime
     * @todo   Implement testSetLastTime().
     */
    public function testSetLastTime()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers App\Entity\User_old::getLastTime
     * @todo   Implement testGetLastTime().
     */
    public function testGetLastTime()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers App\Entity\User_old::setSessionToken
     * @todo   Implement testSetSessionToken().
     */
    public function testSetSessionToken()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers App\Entity\User_old::getSessionToken
     * @todo   Implement testGetSessionToken().
     */
    public function testGetSessionToken()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers App\Entity\User_old::setDateCreation
     * @todo   Implement testSetDateCreation().
     */
    public function testSetDateCreation()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers App\Entity\User_old::getDateCreation
     * @todo   Implement testGetDateCreation().
     */
    public function testGetDateCreation()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers App\Entity\User_old::setUserCreation
     * @todo   Implement testSetUserCreation().
     */
    public function testSetUserCreation()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers App\Entity\User_old::getUserCreation
     * @todo   Implement testGetUserCreation().
     */
    public function testGetUserCreation()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers App\Entity\User_old::setDateModify
     * @todo   Implement testSetDateModify().
     */
    public function testSetDateModify()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers App\Entity\User_old::getDateModify
     * @todo   Implement testGetDateModify().
     */
    public function testGetDateModify()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers App\Entity\User_old::setUserModify
     * @todo   Implement testSetUserModify().
     */
    public function testSetUserModify()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers App\Entity\User_old::getUserModify
     * @todo   Implement testGetUserModify().
     */
    public function testGetUserModify()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
