<?php
namespace App\Tests;

use App\Kernel;
use PHPUnit\Framework\TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2018-01-02 at 16:09:16.
 */
class KernelTest extends TestCase
{

    /**
     * @var Kernel
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Kernel('test',true);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers App\Kernel::getCacheDir
     * @todo   Implement testGetCacheDir().
     */
    public function testGetCacheDir()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers App\Kernel::getLogDir
     * @todo   Implement testGetLogDir().
     */
    public function testGetLogDir()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers App\Kernel::registerBundles
     * @todo   Implement testRegisterBundles().
     */
    public function testRegisterBundles()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers App\Kernel::registerContainerConfiguration
     * @todo   Implement testRegisterContainerConfiguration().
     */
    public function testRegisterContainerConfiguration()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers App\Kernel::loadRoutes
     * @todo   Implement testLoadRoutes().
     */
    public function testLoadRoutes()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
