<?php
namespace App\Tests\EventSubscriber;

use App\EventSubscriber\LocaleSubscriber;
use Doctrine\ORM\EntityManagerInterface;
use PHPUnit\Framework\TestCase;
use Symfony\Component\HttpFoundation\Session\SessionInterface;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2018-01-02 at 16:09:15.
 */
class LocaleSubscriberTest extends TestCase
{

    /**
     * @var LocaleSubscriber
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $defaultLocale = 'en';
        $em = $this->createMock(EntityManagerInterface::class);
        $session = $this->createMock(SessionInterface::class);
        $this->object = new LocaleSubscriber($defaultLocale, $em, $session);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers App\EventSubscriber\LocaleSubscriber::onKernelRequest
     * @todo   Implement testOnKernelRequest().
     */
    public function testOnKernelRequest()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers App\EventSubscriber\LocaleSubscriber::onInteractiveLogin
     * @todo   Implement testOnInteractiveLogin().
     */
    public function testOnInteractiveLogin()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers App\EventSubscriber\LocaleSubscriber::getSubscribedEvents
     * @todo   Implement testGetSubscribedEvents().
     */
    public function testGetSubscribedEvents()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
