<?php
namespace App\Tests\EventSubscriber;

use App\EventSubscriber\TelemetrySubscriber;
use App\Functions\BaseConfig;
use Doctrine\ORM\EntityManagerInterface;
use PHPUnit\Framework\TestCase;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Component\Routing\RouterInterface;
use Symfony\Component\Security\Core\Encoder\EncoderFactoryInterface;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2018-01-02 at 16:09:14.
 */
class TelemetrySubscriberTest extends TestCase
{

    /**
     * @var TelemetrySubscriber
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $em = $this->createMock(EntityManagerInterface::class);
        $encoder = $this->createMock(EncoderFactoryInterface::class);
        $baseConfig = $this->createMock(BaseConfig::class);
        $container = $this->createMock(ContainerInterface::class);
        $routerInterface= $this->createMock(RouterInterface::class);
        $session = $this->createMock(SessionInterface::class);
        $this->object = new TelemetrySubscriber($em, $encoder, $baseConfig, $container, $routerInterface, $session);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers App\EventSubscriber\TelemetrySubscriber::getSubscribedEvents
     * @todo   Implement testGetSubscribedEvents().
     */
    public function testGetSubscribedEvents()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers App\EventSubscriber\TelemetrySubscriber::initDatabase
     * @todo   Implement testInitDatabase().
     */
    public function testInitDatabase()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers App\EventSubscriber\TelemetrySubscriber::verifyDatabase
     * @todo   Implement testVerifyDatabase().
     */
    public function testVerifyDatabase()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers App\EventSubscriber\TelemetrySubscriber::verifyAdminPassword
     * @todo   Implement testVerifyAdminPassword().
     */
    public function testVerifyAdminPassword()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers App\EventSubscriber\TelemetrySubscriber::onKernelRequest
     * @todo   Implement testOnKernelRequest().
     */
    public function testOnKernelRequest()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers App\EventSubscriber\TelemetrySubscriber::onInteractiveLogin
     * @todo   Implement testOnInteractiveLogin().
     */
    public function testOnInteractiveLogin()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
