<?php
namespace App\Functions;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2018-01-02 at 16:08:50.
 */
class BaseConfigTest extends TestCase
{

    /**
     * @var BaseConfig
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new BaseConfig;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers App\Functions\BaseConfig::verifyDatabase
     * @todo   Implement testVerifyDatabase().
     */
    public function testVerifyDatabase()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers App\Functions\BaseConfig::createDatabase
     * @todo   Implement testCreateDatabase().
     */
    public function testCreateDatabase()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
