<?php
namespace App\Tests\Functions;

use App\Functions\UserUtils;
use PHPUnit\Framework\TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2018-01-02 at 16:08:28.
 */
class UserUtilsTest extends TestCase
{

    /**
     * @var UserUtils
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new UserUtils;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers App\Functions\UserUtils::verifyChangePassword
     * @todo   Implement testVerifyChangePassword().
     */
    public function testVerifyChangePassword()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers App\Functions\UserUtils::verifyFirstPassword
     * @todo   Implement testVerifyFirstPassword().
     */
    public function testVerifyFirstPassword()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
