<?php
namespace App\Controller;

use PHPUnit\Framework\TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2018-01-02 at 16:09:15.
 */
class ConfigControllerTest extends TestCase
{

    /**
     * @var ConfigController
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ConfigController;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers App\Controller\ConfigController::configSystem
     * @todo   Implement testConfigSystem().
     */
    public function testConfigSystem()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers App\Controller\ConfigController::confirmDatabaseConfig
     * @todo   Implement testConfirmDatabaseConfig().
     */
    public function testConfirmDatabaseConfig()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers App\Controller\ConfigController::createDatabaseStructure
     * @todo   Implement testCreateDatabaseStructure().
     */
    public function testCreateDatabaseStructure()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers App\Controller\ConfigController::generateRandomString
     * @todo   Implement testGenerateRandomString().
     */
    public function testGenerateRandomString()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers App\Controller\ConfigController::createSystemTables
     * @todo   Implement testCreateSystemTables().
     */
    public function testCreateSystemTables()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers App\Controller\ConfigController::createAdminUser
     * @todo   Implement testCreateAdminUser().
     */
    public function testCreateAdminUser()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers App\Controller\ConfigController::optionsSystemAction
     * @todo   Implement testOptionsSystemAction().
     */
    public function testOptionsSystemAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
