<?php
namespace App\Tests\Controller;

use App\EventSubscriber\TelemetrySubscriber;
use Doctrine\ORM\EntityManagerInterface;
use PHPUnit\Framework\TestCase;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\HttpFoundation\RequestStack;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Component\Security\Core\Encoder\EncoderFactoryInterface;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;
use App\Controller\DefaultController;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2018-01-02 at 16:09:15.
 */
class DefaultControllerTest extends TestCase
{

    /**
     * @var DefaultController
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $em = $this->createMock(EntityManagerInterface::class);
        $encoder = $this->createMock(EncoderFactoryInterface::class);
        $requestStack = $this->createMock(RequestStack::class);
        $session = $this->createMock(SessionInterface::class);
        $container = $this->createMock(ContainerInterface::class);
        $telemetry = $this->createMock(TelemetrySubscriber::class);
        $passencoder = $this->createMock(UserPasswordEncoderInterface::class);
        $this->object = new DefaultController($em, $encoder, $requestStack, $session, $container, $telemetry, $passencoder);
        
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers App\Controller\DefaultController::index
     * @todo   Implement testIndex().
     */
    public function testIndex()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
